### ISSUE TITLE
Confirm observational masks are the same in CMASS NGC and ltu-cmass

### ISSUE THREAD

**Issue by maho3** [maho3/ltu-gobig#16]
There was some concern that the observational masks in the ngc_selection.py step and the CMASS observational sample were different.

![Image](https://github.com/maho3/ltu-gobig/assets/11132524/74e89fb9-e8f4-4e2e-9f96-35221559a7bb)

The goal here is to manually check that they are the same, or else figure out what is missing from the ltu-cmass mask.

**Comment by lavaux** [comment]
There is an obvious wormy feature missing on the left-hand side.

**Comment by maho3** [comment]
Also check obs depth as a function of angle.

**Comment by maho3** [comment]
Here's a comparison of the randoms (after selection cuts) which more clearly shows the problem:


![Image](https://github.com/maho3/ltu-gobig/assets/11132524/a60cb84e-84c0-4209-af7c-9be76968157a)



And a zoom in on the right region, where we are clearly missing a CMASS mask.


![Image](https://github.com/maho3/ltu-gobig/assets/11132524/a53e4ec6-5970-4c7c-bdf6-c7f2bc123b57)

Still not sure what we're missing...

**Comment by maho3** [comment]
It seems this crack at (RA,Dec) ~= (200,33) is also not accounted for in the official CMASS mocks:

Left is mock, right is real data.
![Image](https://github.com/maho3/ltu-gobig/assets/11132524/885dc36b-7a2e-4f35-bea8-4e0e45af1467)

Source: https://arxiv.org/pdf/1509.06404.pdf

However, it does not seem like it could be physical.

**Comment by maho3** [comment]
The completeness maps from the official LSS targeting paper seem to show that the crack is well-covered in completeness (apart from the little blips that we've already masked). So, it is possible that this crack is just physical.

![Image](https://github.com/maho3/ltu-gobig/assets/11132524/9801bd01-8263-4d0a-ac15-63a4da8f16a6)

For future reference, this is a good place to understand the selection function: https://arxiv.org/pdf/1509.06529.pdf

Note, the removal of the large chunk in the LOWZ mask is because they made erroneous targeting for low-redshift galaxies, which doesn't affect the CMASS sample.

So, I'm willing to chalk this down as a physical artifact, and that we can simply keep the mask as-is. That being said, I will check with other people that have worked with this SDSS sample to see if they've done the same.

There are still other things to do to improve the way we are doing `ngc_selection.py`.

- Exclude regions where sampling completeness < 0.7, as in the original CMASS LSS analyses (ref. https://arxiv.org/pdf/1509.06404.pdf)
- Subsample or otherwise reweight angular regions in our mocks by their completeness. Usually this is >~ 97% so there shouldn't be a big impact.

**Comment by maho3** [comment]
Closing with maho3/ltu-cmass#23, but keeping the above notes for reference.
