### ISSUE TITLE
Port Quijote latin_hypercube_HR to ltu-cmass

### ISSUE THREAD

**Issue by maho3** [maho3/ltu-gobig#2]
We want to use [the quijote halos](https://quijote-simulations.readthedocs.io/en/latest/halos.html) to validate the products of the ltu-cmass forward model. We need them in the same format as [the outputs of ltu-cmass halo generation](https://github.com/maho3/ltu-cmass/blob/main/cmass/bias/rho_to_halo.py) so that they can be adopted to the pipeline.

We want the z=0.5 snapshots, since CMASS is z~0.55. We want the HR snapshots, since they go down to LRG-like halos.

**Definition of done**:
- [ ]  A script to adopt the raw Quijote outputs to ltu-cmass OR catalogs of quijote halos uploaded to OSN

**Comment by DeaglanBartlett** [comment]
The halos in the correct format are saved in `/data101/bartlett/quijote/Halos/latin_hypercube_HR/`
